version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/src/alpine/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: nginx

  - package-ecosystem: "docker"
    directory: "/src/debian/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: nginx
