name: nginx

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/nginx.yml'
      - 'nginx/**/Dockerfile'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - '.github/workflows/nginx.yml'
      - 'nginx/**/Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        variant: ["alpine", "debian"]

    env:
      IMAGE_FILE: ./nginx/${{ matrix.variant }}/Dockerfile
      IMAGE_REGISTRY: ghcr.io
      IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/nginx:${{ matrix.variant == 'debian' && 'latest' || matrix.variant }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
          file: ${{ env.IMAGE_FILE }}
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            ENABLED_MODULES=ndk lua brotli headers-more geoip2
          platforms: linux/amd64,linux/arm64
          provenance: false
